In [ ]:
import numpy as np
from numpy import exp, log2
import csv
import tqdm
from tqdm.notebook import tqdm_notebook
import random
np.random.seed(42)

# Data Processing

In [ ]:
dataset = []
class_1_dataset = []
with open('palindrome_data.csv' , 'r') as file:
  lines = file.readlines()
  for line in lines:
    example , label = line.strip().split("\t")
    example = [int(x) for x in example]
    dataset.append((np.array(example),int(label)))
    if int(label) == 1:
      class_1_dataset.append((np.array(example),int(label)))

In [ ]:
dataset

[(array([1, 1, 0, 0, 0, 1, 1, 1, 0, 0]), 0),
 (array([1, 1, 1, 0, 0, 0, 0, 1, 1, 1]), 1),
 (array([0, 1, 0, 1, 0, 1, 1, 1, 0, 0]), 0),
 (array([0, 0, 0, 0, 1, 1, 1, 0, 0, 1]), 0),
 (array([0, 0, 1, 1, 1, 0, 1, 0, 1, 0]), 0),
 (array([0, 1, 0, 0, 1, 0, 0, 0, 1, 0]), 0),
 (array([0, 0, 1, 0, 1, 1, 0, 1, 1, 1]), 0),
 (array([1, 1, 0, 1, 1, 0, 0, 1, 1, 0]), 0),
 (array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1]), 0),
 (array([0, 1, 0, 1, 0, 0, 1, 1, 0, 1]), 0),
 (array([0, 1, 1, 0, 0, 0, 1, 0, 1, 0]), 0),
 (array([0, 1, 1, 0, 1, 1, 1, 0, 1, 1]), 0),
 (array([1, 0, 0, 1, 0, 1, 1, 1, 1, 0]), 0),
 (array([0, 0, 0, 1, 1, 0, 0, 0, 1, 0]), 0),
 (array([1, 0, 1, 0, 1, 1, 1, 1, 0, 1]), 0),
 (array([1, 0, 1, 0, 1, 0, 0, 1, 0, 0]), 0),
 (array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1]), 1),
 (array([0, 1, 0, 1, 0, 1, 1, 1, 0, 1]), 0),
 (array([1, 0, 1, 1, 0, 1, 1, 1, 1, 1]), 0),
 (array([1, 0, 1, 0, 1, 1, 0, 0, 1, 1]), 0),
 (array([0, 1, 0, 0, 0, 1, 1, 1, 1, 1]), 0),
 (array([0, 0, 1, 0, 1, 1, 1, 0, 0, 0]), 0),
 (array([0

In [ ]:
print(len(class_1_dataset))

32


In [ ]:
# append_n_times = 10
# for i in tqdm_notebook(range(append_n_times) , desc = "appending positive examples"):
#   dataset.extend(class_1_dataset)
#   print(len(dataset))

In [ ]:
data = []
labels = []
for example,label in dataset:
  data.append(example)
  labels.append(label)

data,labels

([array([1, 1, 0, 0, 0, 1, 1, 1, 0, 0]),
  array([1, 1, 1, 0, 0, 0, 0, 1, 1, 1]),
  array([0, 1, 0, 1, 0, 1, 1, 1, 0, 0]),
  array([0, 0, 0, 0, 1, 1, 1, 0, 0, 1]),
  array([0, 0, 1, 1, 1, 0, 1, 0, 1, 0]),
  array([0, 1, 0, 0, 1, 0, 0, 0, 1, 0]),
  array([0, 0, 1, 0, 1, 1, 0, 1, 1, 1]),
  array([1, 1, 0, 1, 1, 0, 0, 1, 1, 0]),
  array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1]),
  array([0, 1, 0, 1, 0, 0, 1, 1, 0, 1]),
  array([0, 1, 1, 0, 0, 0, 1, 0, 1, 0]),
  array([0, 1, 1, 0, 1, 1, 1, 0, 1, 1]),
  array([1, 0, 0, 1, 0, 1, 1, 1, 1, 0]),
  array([0, 0, 0, 1, 1, 0, 0, 0, 1, 0]),
  array([1, 0, 1, 0, 1, 1, 1, 1, 0, 1]),
  array([1, 0, 1, 0, 1, 0, 0, 1, 0, 0]),
  array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1]),
  array([0, 1, 0, 1, 0, 1, 1, 1, 0, 1]),
  array([1, 0, 1, 1, 0, 1, 1, 1, 1, 1]),
  array([1, 0, 1, 0, 1, 1, 0, 0, 1, 1]),
  array([0, 1, 0, 0, 0, 1, 1, 1, 1, 1]),
  array([0, 0, 1, 0, 1, 1, 1, 0, 0, 0]),
  array([0, 0, 0, 1, 0, 1, 0, 0, 0, 0]),
  array([0, 1, 0, 1, 1, 1, 0, 0, 1, 0]),
  array([1, 0, 0

# Neural Network

## Linear Layer with Backward Compatibility

This is a more modular code

In [ ]:
class Linearlayer():
    def __init__(self,input_neurons,output_neurons , name = "layer", momentum = None):
        self.weights = np.random.randn(input_neurons,output_neurons)
        self.bias = np.zeros((1,output_neurons))
        self.name = name
        self.momentum = momentum
        self.delta_weights = 0
        self.delta_bias = 0


    def forward(self,inputs):
        self.input = inputs
        # print(f"shape at {self.name}" , inputs.shape)
      # Input is in the form 1*n , weights is n*o so dot product is 1*o
        self.output = np.dot(inputs,self.weights) + self.bias
        return self.output

    # given dE/dnet_layer = delta it calculates dE/dW
    def backward(self, deltas, lr):
      # print(f"starting backward for {self.name}")
      # print(deltas.shape)
      # deltas is of the shape = 1*out, inputs of the shape in*1
      d_error_by_d_weights = np.dot(self.input.T , deltas)
      # in*out matrix

      # d_error_by_d_input will become dE/dnet_layer for previous layer 1*in
      d_error_by_d_input = np.dot(deltas , self.weights.T)
      # 1*out , out*in = 1*in

      d_error_by_d_bias = 1*deltas
      # 1*out

      # Weight Changes
      # check if momentum is there
      if self.momentum is None:
        self.weights -= lr * d_error_by_d_weights
        self.bias -= lr * d_error_by_d_bias
      else:
        self.delta_weights =  lr * d_error_by_d_weights + self.momentum * self.delta_weights
        self.weights -= self.delta_weights

        self.delta_bias = lr * d_error_by_d_bias + self.momentum * self.delta_bias
        self.bias -= self.delta_bias

      # print(f"done backward for {self.name}")

      return d_error_by_d_input




## Activation layer with only softmax and backward compatibility

In [ ]:
class ActivationLayer():
  def __init__(self, name='layer' , activation="sigmoid"):
    self.name = name
    self.activation = activation

  def forward(self, x):
    self.x = x
    if self.activation == "sigmoid":
      return self._sigmoid_activation(x)

    if self.activation == "relu":
      return self._RELU_activation(x)

    return self._softmax_activation(x)

  def _sigmoid_activation(self , x):
    return 1/(1+exp(-x))

  def _derivative_sigmoid_activation(self , x):
    x = self._sigmoid_activation(x)
    return x*(1-x)

  def _softmax_activation(self , x):
    x = exp(x) / np.sum(exp(x))


  def _derivative_softmax_activation(self, x):
    S = self._softmax_activation(x)
    S_vector = S.reshape(S.shape[0],1)
    S_matrix = np.tile(S_vector,S.shape[0])
    S_dir = np.diag(S) - (S_matrix * np.transpose(S_matrix))
    return S_dir


  def _RELU_activation(self, x):
    return x * (x > 0)

  def _derivative_RELU_activation(self, x):
    return 1. * (x > 0)


  def backward(self, deltas, lr):
    # here this will pass the dE/Dnet_out_prev but act has been applied
    # so chain rule dE/net_prev = dE/dnet_out * dnet_out/dnet_prev
    # dE/dnet_prev = deltas * der_of_activation
    # * is pairwise multiplication
    # print(f"starting backward for {self.name}")
    if self.activation == "sigmoid":
      return self._derivative_sigmoid_activation(self.x) * deltas

    if self.activation == "relu":
      return self._derivative_RELU_activation(self.x) * deltas

    return self._derivative_softmax_activation(self.x) * deltas





## Loss Functions

In [ ]:
def binary_cross_entropy_loss_function(predicted,actual):
  if actual == 1:
    return -1 * log2(predicted)
  else:
    return -1*log2(1-predicted)
  # loss_val = -1 * actual * log2(predicted) - 1*(1-actual)*log2(1-predicted)
  # return loss_val



def derivative_binary_cross_entropy_loss_function(predicted , actual):
  if actual == 1:
    return -1 / predicted
  else:
    return 1/(1-predicted)


def weighted_binary_cross_entropy_loss_function(predicted , actual , weight_1 = 10, weight_0 = 1):
  if actual == 1:
    return -1 * weight_1 * log2(predicted)
  else:
    return -1 * weight_0 *log2(1-predicted)

def derivative_weighted_binary_cross_entropy_loss_function(predicted , actual , weight_1 = 5, weight_0 = 1):
  if actual == 1:
    return - weight_1 / predicted
  else:
    return weight_0 /(1-predicted)




def mse_error(predicted , actual):
  return np.square(predicted - actual) / 2

def derivative_mse_error(predicted,output):
  return predicted - output





## Final Neural Network

* 2 Linear layers and their corresponding activation functions

In [ ]:
class NeuralNet():
    def __init__(
        self, input_neurons, hidden_neuron, output_neuron, learning_rate,
        momentum = None,
        activation="sigmoid",
        loss_function = binary_cross_entropy_loss_function,
        derivative_loss_function = derivative_binary_cross_entropy_loss_function):
        self.inputs_neurons = input_neurons
        self.hidden_neuron = hidden_neuron
        self.output_neuron = output_neuron
        self.learning_rate = learning_rate
        self.loss_function = loss_function
        self.activation = activation
        self.derivative_loss_function = derivative_loss_function
        self.momentum = momentum
        self.input_layer = Linearlayer(input_neurons, hidden_neuron , name="input_layer", momentum = momentum)
        self.activation1 = ActivationLayer(name="activation_layer_1" , activation = activation)
        self.output_layer = Linearlayer(hidden_neuron, output_neuron,name="output_layer", momentum = momentum)
        self.activation2 = ActivationLayer(name = "activation_layer_2" , activation="sigmoid")


    def forward(self,input_value):
        self.input_value = input_value
        # dimension is 1*O
        self.hidden_output = self.input_layer.forward(input_value)
        self.hidden_output = self.activation1.forward(self.hidden_output)
        # print(self.hidden_output)
        # dimension is 1*H

        # dimension now is 1*H
        self.output = self.output_layer.forward(self.hidden_output)
        self.output = self.activation2.forward(self.output)
        # print(self.output)
        # dimension is 1*O
        return self.output


    def predict(self , input_value):
        output = self.forward(input_value)
        output = output >= 0.5
        return output


    def train(self, inputs , outputs , epochs):
      learning_rate = self.learning_rate
      print(f"Learning rate is {learning_rate}")
      print_every = epochs // 10

      for i in tqdm_notebook( range(epochs) , desc = "Training Progress"):
        # print(f"Starting {i+1} epoch.")
        error_per_epoch = 0

        for input,output in zip(inputs,outputs):
          input = input.reshape(1 ,input.shape[0])
          out = self.forward(input)
          # calculating loss
          loss = self.loss_function(out , output)
          error_per_epoch += loss

          delta = self.derivative_loss_function(out , output)

          # doing manually but can be done via for loop
          delta = self.activation2.backward(delta , learning_rate)
          delta = self.output_layer.backward(delta , learning_rate)

          delta = self.activation1.backward(delta , learning_rate)
          delta = self.input_layer.backward(delta , learning_rate)

        # print(f"error on epoch: {i+1} is : {error_per_epoch}")
        if (i) % print_every == 0:
          print(f"error on epoch: {i} is : {error_per_epoch}")






# Training with K folds

Stratified K-Fold Cross-Validation: If we have skewed data with 80-90% data of one class and remaining of the other class. There is a class imbalance. If we will use k-fold cv then most of the folds will be with first class. To maintain this imbalance of 90:10 in all folds, we use stratified k fold approach.

When random_state is fixed integer and shuffle is True, the set of train and test data will be the same for each execution.

In [ ]:

def predict_output(model , example):
    example = np.array(example)
    pred = model.predict(example)
    print(pred)


def get_data(data , list_of_index):
  data_list = []
  for index in list_of_index:
    data_list.append(data[index])
  return data_list


def add_sample_data(dataset, labels, label_to_add, times=5):
  dataset_to_add = []
  labels_to_add = []
  for example,label in zip(dataset,labels):
    if label == label_to_add:
      dataset_to_add.append(example)
      labels_to_add.append(label)

  for i in tqdm_notebook(range(times) , desc= "adding dataset"):
    dataset.extend(dataset_to_add)
    labels.extend(labels_to_add)

  print("New Length " , len(dataset))

  return dataset, labels



def shuffle_dataset(data, labels):
  combined_array = []
  for example,label in zip(data,labels):
    combined_array.append((example,label))

  random.shuffle(combined_array)
  new_data = []
  new_labels = []

  for example,label in combined_array:
    new_data.append(example)
    new_labels.append(label)

  return new_data, new_labels



def train_k_fold(input_neurons, hidden_neuron, output_neuron, learning_rate,
                 data, labels,
                 activation = "sigmoid", momentum = None,
                 folds=5, epochs = 100,
                 loss_function = binary_cross_entropy_loss_function,
                 derivative_loss_function = derivative_binary_cross_entropy_loss_function,
                 models_list = None):
  from sklearn.model_selection import StratifiedKFold
  from sklearn.metrics import classification_report
  from sklearn.metrics import accuracy_score

  target_names = ["not palindrome" , "palindrome"]
  startified_k_fold = StratifiedKFold(n_splits=folds ,shuffle = True)

  fold = 1

  for train_index,test_index in startified_k_fold.split(data,labels):
    print(f"""


    Starting Training on fold : {fold}

    Model params = {input_neurons, hidden_neuron, output_neuron, learning_rate,loss_function , momentum}
    """)
    # np.random.seed(42 + fold)
    model = NeuralNet(input_neurons, hidden_neuron, output_neuron, learning_rate,
                      momentum = momentum,
                      activation = activation,
                      loss_function = loss_function,
                      derivative_loss_function = derivative_loss_function)


    training_data = get_data(data,train_index)
    training_labels = get_data(labels,train_index)
    test_data = get_data(data , test_index)
    test_labels = get_data(labels , test_index)


    training_data , training_labels = add_sample_data(training_data, training_labels , 1 , 5)

    training_data , training_labels = shuffle_dataset(training_data , training_labels)

    model.train(training_data, np.array(training_labels , dtype = "int64") , epochs)
    # Training Stats
    predictions = model.predict(training_data)
    predictions = predictions.reshape(predictions.shape[0])
    actual_labels = np.array(training_labels) == 1
    report = classification_report(actual_labels, predictions, target_names=target_names)

    print("\n\nReport For Training\n\n")
    print(report)

    print(accuracy_score(actual_labels , predictions))

    # Testing Stats

    predictions = model.predict(test_data)
    predictions = predictions.reshape(predictions.shape[0])
    actual_labels = np.array(test_labels) == 1
    report = classification_report(actual_labels, predictions, target_names=target_names)

    print("\n\nReport For Testing\n\n")
    print(report)


    print(accuracy_score(actual_labels , predictions))


    print("input : 0,1,0,0,0,0,0,0,1,0 |", predict_output(model , [0,1,0,0,0,0,0,0,1,0]))
    print("input : 0,1,0,0,0,0,0,0,1,1 |", predict_output(model , [0,1,0,0,0,0,0,0,1,1]))
    print("input : 0,1,0,0,1,1,0,0,1,0 |", predict_output(model , [0,1,0,0,1,1,0,0,1,0]))
    print("input : 1,0,0,0,0,0,0,0,1,0 |", predict_output(model , [1,0,0,0,0,0,0,0,1,0]))
    print("input : 0,0,1,0,0,0,0,1,0,0 |", predict_output(model , [0,0,1,0,0,0,0,1,0,0]))

    fold+=1
    if models_list is not None:
      models_list.append(model)








## Defining Neural Network

### Network 1 with 5 hidden neurons
binary cross entropy loss

In [ ]:
train_k_fold(input_neurons = 10 ,
             hidden_neuron = 5 ,
             output_neuron= 1 ,
             learning_rate= 0.1 ,
            #  momentum = 0.1,
             activation="relu",
             data = data ,
             labels = labels ,
             epochs=500)




    Starting Training on fold : 1

    Model params = (10, 5, 1, 0.1, <function binary_cross_entropy_loss_function at 0x7a69cb8328c0>, None)
    


adding dataset:   0%|          | 0/5 [00:00<?, ?it/s]

New Length  949
Learning rate is 0.1


Training Progress:   0%|          | 0/500 [00:00<?, ?it/s]

error on epoch: 0 is : [[671.26825207]]
error on epoch: 50 is : [[1.41913059]]
error on epoch: 100 is : [[0.59691658]]
error on epoch: 150 is : [[0.37152271]]
error on epoch: 200 is : [[0.26772231]]
error on epoch: 250 is : [[0.20829119]]
error on epoch: 300 is : [[0.16787056]]
error on epoch: 350 is : [[0.1405544]]
error on epoch: 400 is : [[0.1208427]]
error on epoch: 450 is : [[0.10588762]]


Report For Training


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       793
    palindrome       1.00      1.00      1.00       156

      accuracy                           1.00       949
     macro avg       1.00      1.00      1.00       949
  weighted avg       1.00      1.00      1.00       949

1.0


Report For Testing


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       199
    palindrome       1.00      1.00      1.00         6

      accuracy                           1.

adding dataset:   0%|          | 0/5 [00:00<?, ?it/s]

New Length  949
Learning rate is 0.1


Training Progress:   0%|          | 0/500 [00:00<?, ?it/s]

error on epoch: 0 is : [[554.75222333]]
error on epoch: 50 is : [[1.16331747]]
error on epoch: 100 is : [[0.52484482]]
error on epoch: 150 is : [[0.33340327]]
error on epoch: 200 is : [[0.24237287]]
error on epoch: 250 is : [[0.18961884]]
error on epoch: 300 is : [[0.15527719]]
error on epoch: 350 is : [[0.13119442]]
error on epoch: 400 is : [[0.11341563]]
error on epoch: 450 is : [[0.09975842]]


Report For Training


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       793
    palindrome       1.00      1.00      1.00       156

      accuracy                           1.00       949
     macro avg       1.00      1.00      1.00       949
  weighted avg       1.00      1.00      1.00       949

1.0


Report For Testing


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       199
    palindrome       1.00      1.00      1.00         6

      accuracy                           

adding dataset:   0%|          | 0/5 [00:00<?, ?it/s]

New Length  944
Learning rate is 0.1


Training Progress:   0%|          | 0/500 [00:00<?, ?it/s]

error on epoch: 0 is : [[659.11053915]]
error on epoch: 50 is : [[123.59262754]]
error on epoch: 100 is : [[101.92946561]]
error on epoch: 150 is : [[71.61597365]]
error on epoch: 200 is : [[55.28397365]]
error on epoch: 250 is : [[52.5187954]]
error on epoch: 300 is : [[52.67223622]]
error on epoch: 350 is : [[1.26382065]]
error on epoch: 400 is : [[0.56676101]]
error on epoch: 450 is : [[0.36637858]]


Report For Training


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       794
    palindrome       1.00      1.00      1.00       150

      accuracy                           1.00       944
     macro avg       1.00      1.00      1.00       944
  weighted avg       1.00      1.00      1.00       944

1.0


Report For Testing


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       198
    palindrome       1.00      1.00      1.00         7

      accuracy                    

adding dataset:   0%|          | 0/5 [00:00<?, ?it/s]

New Length  944
Learning rate is 0.1


Training Progress:   0%|          | 0/500 [00:00<?, ?it/s]

error on epoch: 0 is : [[502.11530788]]
error on epoch: 50 is : [[0.77168899]]
error on epoch: 100 is : [[0.35315359]]
error on epoch: 150 is : [[0.22883521]]
error on epoch: 200 is : [[0.16860217]]
error on epoch: 250 is : [[0.13309461]]
error on epoch: 300 is : [[0.10970364]]
error on epoch: 350 is : [[0.09308576]]
error on epoch: 400 is : [[0.08068159]]
error on epoch: 450 is : [[0.07116124]]


Report For Training


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       794
    palindrome       1.00      1.00      1.00       150

      accuracy                           1.00       944
     macro avg       1.00      1.00      1.00       944
  weighted avg       1.00      1.00      1.00       944

1.0


Report For Testing


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       198
    palindrome       1.00      1.00      1.00         7

      accuracy                           

adding dataset:   0%|          | 0/5 [00:00<?, ?it/s]

New Length  950
Learning rate is 0.1


Training Progress:   0%|          | 0/500 [00:00<?, ?it/s]

error on epoch: 0 is : [[525.03046187]]
error on epoch: 50 is : [[0.74958213]]
error on epoch: 100 is : [[0.35005949]]
error on epoch: 150 is : [[0.2255078]]
error on epoch: 200 is : [[0.16539632]]
error on epoch: 250 is : [[0.13017922]]
error on epoch: 300 is : [[0.10710213]]
error on epoch: 350 is : [[0.09084854]]
error on epoch: 400 is : [[0.07880202]]
error on epoch: 450 is : [[0.06952004]]


Report For Training


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       794
    palindrome       1.00      1.00      1.00       156

      accuracy                           1.00       950
     macro avg       1.00      1.00      1.00       950
  weighted avg       1.00      1.00      1.00       950

1.0


Report For Testing


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       198
    palindrome       1.00      1.00      1.00         6

      accuracy                           1

### same network without momentum

In [ ]:
train_k_fold(input_neurons = 10 ,
             hidden_neuron = 5 ,
             output_neuron= 1 ,
             learning_rate= 0.1 ,
             data = data ,
             labels = labels ,
             epochs=500)




    Starting Training

    Model params = (10, 5, 1, 0.1, <function binary_cross_entropy_loss_function at 0x7e86072eb910>, None)
    
Learning rate is 0.1


Training Progress:   0%|          | 0/500 [00:00<?, ?it/s]

error on epoch: 0 is : [[245.12425189]]
error on epoch: 50 is : [[108.55064091]]
error on epoch: 100 is : [[21.45191947]]
error on epoch: 150 is : [[7.51653815]]
error on epoch: 200 is : [[4.07161367]]
error on epoch: 250 is : [[2.66518806]]
error on epoch: 300 is : [[1.9415084]]
error on epoch: 350 is : [[1.50979557]]
error on epoch: 400 is : [[1.22652773]]
error on epoch: 450 is : [[1.02804409]]


Report For Training


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       793
    palindrome       1.00      1.00      1.00       282

      accuracy                           1.00      1075
     macro avg       1.00      1.00      1.00      1075
  weighted avg       1.00      1.00      1.00      1075



Report For Testing


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       199
    palindrome       1.00      1.00      1.00        70

      accuracy                           1.

Training Progress:   0%|          | 0/500 [00:00<?, ?it/s]

error on epoch: 0 is : [[240.96504918]]
error on epoch: 50 is : [[69.46507545]]
error on epoch: 100 is : [[10.68394494]]
error on epoch: 150 is : [[4.91269544]]
error on epoch: 200 is : [[3.00558961]]
error on epoch: 250 is : [[2.0792846]]
error on epoch: 300 is : [[1.55536594]]
error on epoch: 350 is : [[1.22802127]]
error on epoch: 400 is : [[1.00782803]]
error on epoch: 450 is : [[0.85113275]]


Report For Training


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       793
    palindrome       1.00      1.00      1.00       282

      accuracy                           1.00      1075
     macro avg       1.00      1.00      1.00      1075
  weighted avg       1.00      1.00      1.00      1075



Report For Testing


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       199
    palindrome       1.00      1.00      1.00        70

      accuracy                           1.0

Training Progress:   0%|          | 0/500 [00:00<?, ?it/s]

error on epoch: 0 is : [[244.92472873]]
error on epoch: 50 is : [[126.17303717]]
error on epoch: 100 is : [[53.41893309]]
error on epoch: 150 is : [[23.87666132]]
error on epoch: 200 is : [[13.96600502]]
error on epoch: 250 is : [[9.77264268]]
error on epoch: 300 is : [[7.46836535]]
error on epoch: 350 is : [[6.01922921]]
error on epoch: 400 is : [[5.02403226]]
error on epoch: 450 is : [[4.29844071]]


Report For Training


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       794
    palindrome       0.99      1.00      0.99       281

      accuracy                           1.00      1075
     macro avg       0.99      1.00      1.00      1075
  weighted avg       1.00      1.00      1.00      1075



Report For Testing


                precision    recall  f1-score   support

not palindrome       1.00      0.99      0.99       198
    palindrome       0.97      1.00      0.99        71

      accuracy                          

Training Progress:   0%|          | 0/500 [00:00<?, ?it/s]

error on epoch: 0 is : [[230.55093329]]
error on epoch: 50 is : [[166.16883892]]
error on epoch: 100 is : [[84.1195996]]
error on epoch: 150 is : [[47.71722645]]
error on epoch: 200 is : [[33.57808576]]
error on epoch: 250 is : [[24.24193912]]
error on epoch: 300 is : [[19.77242114]]
error on epoch: 350 is : [[19.07633525]]
error on epoch: 400 is : [[16.14026074]]
error on epoch: 450 is : [[9.30222238]]


Report For Training


                precision    recall  f1-score   support

not palindrome       1.00      0.99      0.99       794
    palindrome       0.97      1.00      0.99       281

      accuracy                           0.99      1075
     macro avg       0.99      0.99      0.99      1075
  weighted avg       0.99      0.99      0.99      1075



Report For Testing


                precision    recall  f1-score   support

not palindrome       1.00      0.95      0.98       198
    palindrome       0.89      1.00      0.94        71

      accuracy                       

Training Progress:   0%|          | 0/500 [00:00<?, ?it/s]

error on epoch: 0 is : [[236.72164096]]
error on epoch: 50 is : [[119.66851262]]
error on epoch: 100 is : [[63.28700922]]
error on epoch: 150 is : [[32.50237847]]
error on epoch: 200 is : [[24.29133956]]
error on epoch: 250 is : [[13.45823039]]
error on epoch: 300 is : [[12.06255508]]
error on epoch: 350 is : [[9.30333215]]
error on epoch: 400 is : [[6.12440014]]
error on epoch: 450 is : [[4.83025998]]


Report For Training


                precision    recall  f1-score   support

not palindrome       1.00      0.98      0.99       794
    palindrome       0.95      1.00      0.98       282

      accuracy                           0.99      1076
     macro avg       0.98      0.99      0.98      1076
  weighted avg       0.99      0.99      0.99      1076



Report For Testing


                precision    recall  f1-score   support

not palindrome       1.00      0.98      0.99       198
    palindrome       0.95      1.00      0.97        70

      accuracy                        

### Network 2 with 4 hidden neurons
binary cross entropy loss

In [ ]:
train_k_fold(input_neurons = 10 ,
             hidden_neuron = 4 ,
             output_neuron= 1 ,
             learning_rate= 0.1 ,
             data = data ,
             labels = labels ,
            #  momentum = 0.01,
             activation = "relu",
             epochs=500)

### Network 3 with 3 hidden neurons
binary cross entropy loss

In [ ]:
model_3_list = []

train_k_fold(input_neurons = 10 ,
             hidden_neuron = 3 ,
             output_neuron= 1 ,
             learning_rate= 0.15 ,
            #  momentum = 0.01,
             activation = "relu",
             data = data ,
             labels = labels ,
             epochs=600,
             models_list = model_3_list)




    Starting Training on fold : 1

    Model params = (10, 3, 1, 0.15, <function binary_cross_entropy_loss_function at 0x7a69cb8328c0>, None)
    


adding dataset:   0%|          | 0/5 [00:00<?, ?it/s]

New Length  949
Learning rate is 0.15


Training Progress:   0%|          | 0/600 [00:00<?, ?it/s]

error on epoch: 0 is : [[603.70221776]]
error on epoch: 60 is : [[0.45049161]]
error on epoch: 120 is : [[0.20915016]]
error on epoch: 180 is : [[0.13521622]]
error on epoch: 240 is : [[0.09955774]]
error on epoch: 300 is : [[0.07859381]]
error on epoch: 360 is : [[0.06483752]]
error on epoch: 420 is : [[0.05511991]]
error on epoch: 480 is : [[0.04789785]]
error on epoch: 540 is : [[0.04232345]]


Report For Training


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       793
    palindrome       1.00      1.00      1.00       156

      accuracy                           1.00       949
     macro avg       1.00      1.00      1.00       949
  weighted avg       1.00      1.00      1.00       949

1.0


Report For Testing


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       199
    palindrome       1.00      1.00      1.00         6

      accuracy                           

adding dataset:   0%|          | 0/5 [00:00<?, ?it/s]

New Length  949
Learning rate is 0.15


Training Progress:   0%|          | 0/600 [00:00<?, ?it/s]

error on epoch: 0 is : [[486.45187544]]
error on epoch: 60 is : [[0.47549902]]
error on epoch: 120 is : [[0.21105524]]
error on epoch: 180 is : [[0.13467039]]
error on epoch: 240 is : [[0.09851621]]
error on epoch: 300 is : [[0.07749356]]
error on epoch: 360 is : [[0.06377047]]
error on epoch: 420 is : [[0.0541227]]
error on epoch: 480 is : [[0.04697636]]
error on epoch: 540 is : [[0.04147297]]


Report For Training


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       793
    palindrome       1.00      1.00      1.00       156

      accuracy                           1.00       949
     macro avg       1.00      1.00      1.00       949
  weighted avg       1.00      1.00      1.00       949

1.0


Report For Testing


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       199
    palindrome       1.00      1.00      1.00         6

      accuracy                           1

adding dataset:   0%|          | 0/5 [00:00<?, ?it/s]

New Length  944
Learning rate is 0.15


Training Progress:   0%|          | 0/600 [00:00<?, ?it/s]

error on epoch: 0 is : [[595.20011812]]
error on epoch: 60 is : [[127.35293573]]
error on epoch: 120 is : [[98.21201308]]
error on epoch: 180 is : [[90.87743003]]
error on epoch: 240 is : [[14.85079508]]
error on epoch: 300 is : [[14.6972032]]
error on epoch: 360 is : [[14.67407416]]
error on epoch: 420 is : [[14.65787394]]
error on epoch: 480 is : [[14.6499892]]
error on epoch: 540 is : [[14.64982952]]


Report For Training


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       794
    palindrome       0.99      1.00      0.99       150

      accuracy                           1.00       944
     macro avg       0.99      1.00      1.00       944
  weighted avg       1.00      1.00      1.00       944

0.9978813559322034


Report For Testing


                precision    recall  f1-score   support

not palindrome       1.00      0.99      0.99       198
    palindrome       0.78      1.00      0.88         7

      accuracy    

adding dataset:   0%|          | 0/5 [00:00<?, ?it/s]

New Length  944
Learning rate is 0.15


Training Progress:   0%|          | 0/600 [00:00<?, ?it/s]

error on epoch: 0 is : [[579.68307954]]
error on epoch: 60 is : [[162.5747107]]
error on epoch: 120 is : [[90.37724996]]
error on epoch: 180 is : [[21.95719975]]
error on epoch: 240 is : [[21.69271046]]
error on epoch: 300 is : [[21.65811678]]
error on epoch: 360 is : [[21.64908729]]
error on epoch: 420 is : [[21.64039344]]
error on epoch: 480 is : [[21.6332217]]
error on epoch: 540 is : [[21.63139316]]


Report For Training


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       794
    palindrome       0.98      1.00      0.99       150

      accuracy                           1.00       944
     macro avg       0.99      1.00      0.99       944
  weighted avg       1.00      1.00      1.00       944

0.996822033898305


Report For Testing


                precision    recall  f1-score   support

not palindrome       1.00      0.98      0.99       198
    palindrome       0.64      1.00      0.78         7

      accuracy     

adding dataset:   0%|          | 0/5 [00:00<?, ?it/s]

New Length  950
Learning rate is 0.15


Training Progress:   0%|          | 0/600 [00:00<?, ?it/s]

error on epoch: 0 is : [[594.78600856]]
error on epoch: 60 is : [[133.86091666]]
error on epoch: 120 is : [[87.72096404]]
error on epoch: 180 is : [[100.75120803]]
error on epoch: 240 is : [[30.45408887]]
error on epoch: 300 is : [[28.51243574]]
error on epoch: 360 is : [[0.56024437]]
error on epoch: 420 is : [[0.26870271]]
error on epoch: 480 is : [[0.17674744]]
error on epoch: 540 is : [[0.13158382]]


Report For Training


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       794
    palindrome       1.00      1.00      1.00       156

      accuracy                           1.00       950
     macro avg       1.00      1.00      1.00       950
  weighted avg       1.00      1.00      1.00       950

1.0


Report For Testing


                precision    recall  f1-score   support

not palindrome       1.00      0.98      0.99       198
    palindrome       0.67      1.00      0.80         6

      accuracy                    

### Network 4 with 2 hidden neurons
binary cross entropy loss

In [ ]:
models_2_list = []
train_k_fold(input_neurons = 10 ,
             hidden_neuron = 2 ,
             output_neuron= 1 ,
             learning_rate= 0.2,
             data = data ,
             labels = labels ,
             momentum = 0.01,
             activation = "relu",
            #  loss_function=weighted_binary_cross_entropy_loss_function,
            #  derivative_loss_function=derivative_weighted_binary_cross_entropy_loss_function,
             epochs=2000,
             models_list = models_2_list)




    Starting Training on fold : 1

    Model params = (10, 2, 1, 0.2, <function binary_cross_entropy_loss_function at 0x7a69cb8328c0>, 0.01)
    


adding dataset:   0%|          | 0/5 [00:00<?, ?it/s]

New Length  949
Learning rate is 0.2


Training Progress:   0%|          | 0/2000 [00:00<?, ?it/s]

error on epoch: 0 is : [[592.21558737]]
error on epoch: 200 is : [[84.24166307]]
error on epoch: 400 is : [[89.06621091]]
error on epoch: 600 is : [[8.88831804]]
error on epoch: 800 is : [[8.8815436]]
error on epoch: 1000 is : [[8.87969987]]
error on epoch: 1200 is : [[8.87854519]]


<ipython-input-30-1ca5ddd9f947>:17: RuntimeWarning: overflow encountered in exp
  return 1/(1+exp(-x))


error on epoch: 1400 is : [[8.87773564]]
error on epoch: 1600 is : [[8.87758484]]
error on epoch: 1800 is : [[8.87720081]]


Report For Training


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       793
    palindrome       0.99      1.00      1.00       156

      accuracy                           1.00       949
     macro avg       1.00      1.00      1.00       949
  weighted avg       1.00      1.00      1.00       949

0.9989462592202318


Report For Testing


                precision    recall  f1-score   support

not palindrome       1.00      0.98      0.99       199
    palindrome       0.67      1.00      0.80         6

      accuracy                           0.99       205
     macro avg       0.83      0.99      0.90       205
  weighted avg       0.99      0.99      0.99       205

0.9853658536585366
[[ True]]
input : 0,1,0,0,0,0,0,0,1,0 | None
[[False]]
input : 0,1,0,0,0,0,0,0,1,1 | None
[[ True]]
input : 0,1,0,

adding dataset:   0%|          | 0/5 [00:00<?, ?it/s]

New Length  949
Learning rate is 0.2


Training Progress:   0%|          | 0/2000 [00:00<?, ?it/s]

error on epoch: 0 is : [[641.62371165]]
error on epoch: 200 is : [[45.69225721]]
error on epoch: 400 is : [[24.62909885]]
error on epoch: 600 is : [[8.89119205]]
error on epoch: 800 is : [[8.88253324]]
error on epoch: 1000 is : [[8.87984713]]
error on epoch: 1200 is : [[8.8786748]]
error on epoch: 1400 is : [[8.87810379]]
error on epoch: 1600 is : [[8.87750775]]
error on epoch: 1800 is : [[8.87713649]]


Report For Training


                precision    recall  f1-score   support

not palindrome       1.00      1.00      1.00       793
    palindrome       0.99      1.00      1.00       156

      accuracy                           1.00       949
     macro avg       1.00      1.00      1.00       949
  weighted avg       1.00      1.00      1.00       949

0.9989462592202318


Report For Testing


                precision    recall  f1-score   support

not palindrome       1.00      0.99      0.99       199
    palindrome       0.75      1.00      0.86         6

      accuracy     

adding dataset:   0%|          | 0/5 [00:00<?, ?it/s]

New Length  944
Learning rate is 0.2


Training Progress:   0%|          | 0/2000 [00:00<?, ?it/s]

error on epoch: 0 is : [[521.13346941]]
error on epoch: 200 is : [[98.03003245]]
error on epoch: 400 is : [[27.32276779]]
error on epoch: 600 is : [[27.30846587]]
error on epoch: 800 is : [[27.30409828]]
error on epoch: 1000 is : [[27.30236084]]
error on epoch: 1200 is : [[27.30113905]]
error on epoch: 1400 is : [[27.30089252]]
error on epoch: 1600 is : [[27.30049723]]
error on epoch: 1800 is : [[27.30074441]]


Report For Training


                precision    recall  f1-score   support

not palindrome       1.00      0.99      1.00       794
    palindrome       0.97      1.00      0.99       150

      accuracy                           1.00       944
     macro avg       0.99      1.00      0.99       944
  weighted avg       1.00      1.00      1.00       944

0.9957627118644068


Report For Testing


                precision    recall  f1-score   support

not palindrome       1.00      0.99      0.99       198
    palindrome       0.78      1.00      0.88         7

      accur

adding dataset:   0%|          | 0/5 [00:00<?, ?it/s]

New Length  944
Learning rate is 0.2


Training Progress:   0%|          | 0/2000 [00:00<?, ?it/s]

error on epoch: 0 is : [[640.33402226]]
error on epoch: 200 is : [[570.53015161]]
error on epoch: 400 is : [[570.58039603]]
error on epoch: 600 is : [[570.61070345]]
error on epoch: 800 is : [[570.6182678]]
error on epoch: 1000 is : [[570.62281686]]
error on epoch: 1200 is : [[570.62160578]]
error on epoch: 1400 is : [[570.62153191]]
error on epoch: 1600 is : [[570.62170826]]
error on epoch: 1800 is : [[570.62129494]]


Report For Training


                precision    recall  f1-score   support

not palindrome       0.86      1.00      0.92       794
    palindrome       0.90      0.12      0.21       150

      accuracy                           0.86       944
     macro avg       0.88      0.56      0.57       944
  weighted avg       0.86      0.86      0.81       944

0.8580508474576272


Report For Testing


                precision    recall  f1-score   support

not palindrome       0.97      0.99      0.98       198
    palindrome       0.00      0.00      0.00         7

   

adding dataset:   0%|          | 0/5 [00:00<?, ?it/s]

New Length  950
Learning rate is 0.2


Training Progress:   0%|          | 0/2000 [00:00<?, ?it/s]

error on epoch: 0 is : [[646.57492422]]
error on epoch: 200 is : [[493.62058046]]
error on epoch: 400 is : [[494.43625552]]
error on epoch: 600 is : [[493.61090905]]
error on epoch: 800 is : [[493.61006255]]
error on epoch: 1000 is : [[493.60995505]]
error on epoch: 1200 is : [[493.6099125]]
error on epoch: 1400 is : [[493.60988962]]
error on epoch: 1600 is : [[493.60987531]]
error on epoch: 1800 is : [[493.6098655]]


Report For Training


                precision    recall  f1-score   support

not palindrome       0.84      1.00      0.91       794
    palindrome       0.00      0.00      0.00       156

      accuracy                           0.84       950
     macro avg       0.42      0.50      0.46       950
  weighted avg       0.70      0.84      0.76       950

0.8357894736842105


Report For Testing


                precision    recall  f1-score   support

not palindrome       0.97      1.00      0.99       198
    palindrome       0.00      0.00      0.00         6

    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classif

### Network 3 with 5 hidden neurons
mse cross entropy loss

In [ ]:
train_k_fold(input_neurons = 10 ,
             hidden_neuron = 5 ,
             output_neuron= 1 ,
             learning_rate= 0.1 ,
             data = data ,
             labels = labels ,
             loss_function=mse_error,
             derivative_loss_function=derivative_mse_error,
             epochs=500)